---
- name: Update Debian
  hosts: all

  tasks:
    - name: Perform package list update
      ansible.builtin.apt:
        update_cache: true
    - name: Peform package upgrade
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Remove useless packages from cache
      ansible.builtin.apt:
        autoclean: true
    - name: Remove orphane depedencies
      ansible.builtin.apt:
        autoremove: true