---
- name: Update servers
  hosts: all

  tasks:
    - name: Apt update
      apt:
        update_cache: true
    - name: Peform package upgrade
      apt:
        name: "*"
        state: latest
    - name: Remove useless packages from cache
      apt:
        autoclean: true
    - name: Remove orphane depedencies
      apt:
        autoremove: true
