all:
  vars:
    authkey_path: '/root/.ssh'
  hosts:
    spider-prxmx:
      ansible_host: 192.168.100.22
      ansible_port: 10022
      ansible_user: root
    komatoz-prxmx:
      ansible_host: 192.168.100.31
      ansible_port: 10022
      ansible_user: root
    pihole-dns1:
      ansible_host: 192.168.100.8
      ansible_user: root
      ansible_port: 10022
    home-assistant-dc1:
      ansible_host: 192.168.100.35
      ansible_user: root
    saturn-builder-gitlab:
      ansible_host: 192.168.100.53
      ansible_user: root
    pkg-repo:
      ansible_host: 192.168.100.16
      ansible_user: root
    km-gn1: 
      ansible_host: 192.168.100.29
      ansible_user: root

physical:
  hosts:
    spider-prxmx:
    komatoz-prxmx:

virtual:
  hosts:
    pihole-dns1:
    home-assistant-dc1:
    saturn-builder-gitlab:
    pkg-repo:
    km-gn1:
