all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    proxmu1:
      ansible_host: 192.168.100.23
    pihole-master:
      ansible_host: 192.168.100.5
    forgejo-prod1:
      ansible_host: 192.168.100.55
    h-MU-kraken-slave:
      ansible_host: 192.168.100.11
    h-PX1-jellyfin-prod:
      ansible_host: 192.168.100.100


physical:
  hosts:
    proxmu1:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    pihole-master:
    forgejo-prod1:
    h-MU-kraken-slave:
    h-PX1-jellyfin-prod: