all:
  vars:
    authkey_path: '/root/.ssh'
    ansible_user: root
  hosts:
    spider-prxmx:
      ansible_host: 192.168.100.22
    pihole-dns2:
      ansible_host: 192.168.100.8

physical:
  hosts:
    spider-prxmx:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    pihole-dns2:
