all:
  vars:
    authkey_path: '/root/.ssh'
    ansible_user: root
  hosts:
    spider-proxy:
      ansible_host: 192.168.0.92
    spider-prxmx:
      ansible_host: 192.168.0.22
      ansible_port: 10022
    pihole-dns1:
      ansible_host: 192.168.0.8
      ansible_port: 10022
    spider-gn1:
      ansible_host: 192.168.0.35

physical:
  hosts:
    spider-prxmx:

virtual:
  hosts:
    spider-proxy:
    pihole-dns1:
    spider-gn1:
