all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    proxmu1:
      ansible_host: 192.168.100.23
    whonnik:
      ansible_host: 192.168.100.24
    ansible:
      ansible_host: 192.168.100.7
    adguard-master:
      ansible_host: 192.168.100.5
    h-MU-kraken-slave:
      ansible_host: 192.168.100.11
    px1-jellyfin-prod:
      ansible_host: 192.168.100.100
    px-docker-cluster1:
      ansible_host: 192.168.100.8

physical:
  hosts:
    proxmu1:
    whonnik:
  vars:
    ansible_port: 1922

opensuse:
  hosts:
    px1-jellyfin-prod:
  vars:
    ansible_user: root
    gather_facts: no

virtual:
  hosts:
    adguard-master:
    h-MU-kraken-slave:
    ansible:
    px1-jellyfin-prod:
    px-docker-cluster1:

syncthing:
  hosts:
    h-MU-kraken-slave:
