all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    proxmu1:
      ansible_host: 192.168.100.23
    adguard-master:
      ansible_host: 192.168.100.5
    gitlab:
      ansible_host: 192.168.100.55
    h-MU-kraken-slave:
      ansible_host: 192.168.100.11
    h-PX1-jellyfin-prod:
      ansible_host: 192.168.100.100
    gitlab-runner-2025:
      ansible_host: 192.168.100.73
    bastion1:
      ansible_host: 192.168.100.12

physical:
  hosts:
    proxmu1:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    adguard-master:
    h-MU-kraken-slave:
    h-PX1-jellyfin-prod:
    gitlab:
    gitlab-runner-2025:
    bastion1:
