all:
  vars:
    authkey_path: '/root/.ssh'
  hosts:
    spider:
      ansible_host: 192.168.100.22
      ansible_port: 10022
      ansible_user: root
    pihole:
      ansible_host: 192.168.100.8
      ansible_user: root
      ansible_port: 10022
    raif-lab:
      ansible_host: 192.168.100.74
      ansible_user: root
    dataz:
      ansible_host: 192.168.100.35
      ansible_user: root
    home-assitant:
      ansible_host: 192.168.100.35
      ansible_user: root
    saturn-builder-gitlab:
      ansible_host: 192.168.100.53
      ansible_user: root

physical:
  hosts:
    spider:

virtual:
  hosts:
    pihole:
    raif-lab:
    dataz:
    home-assitant:
    saturn-builder-gitlab:
