all:
  vars:
    ansible_user: root
  hosts:
    apollo-router:
      ansible_host: 192.168.100.22
    pihole-master:
      ansible_host: 192.168.100.5
    pihole-slave:
      ansible_host: 192.168.100.6
    forgejo-prod1:
      ansible_host: 192.168.100.53

physical:
  hosts:
    apollo-router:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    pihole-master:
    pihole-slave:
    forgejo-prod1:
