all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    apollo-router:
      ansible_host: 192.168.100.22
    pihole-master:
      ansible_host: 192.168.100.5
    forgejo-prod1:
      ansible_host: 192.168.100.53
    h-MU-kraken-slave:
      ansible_host: 192.168.100.11
    h-MU-forgejo-runner:
      ansible_host: 10.10.10.55
      ansible_ssh_common_args: '-o ProxyCommand="ssh -p 1922 -W %h:%p -q root@apollo-router"'

physical:
  hosts:
    apollo-router:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    pihole-master:
    forgejo-prod1:
    h-MU-kraken-slave:
