all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    proxmu1:
      ansible_host: 192.168.100.23
    whonnik:
      ansible_host: 192.168.100.24
    adguard-master:
      ansible_host: 192.168.100.5
    h-MU-kraken-slave:
      ansible_host: 192.168.100.11


physical:
  hosts:
    proxmu1:
    whonnik:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    adguard-master:
    h-MU-kraken-slave:
