all:
  vars:
    authkey_path: '/root/.ssh'
  hosts:
    spider-prxmx:
      ansible_host: 192.168.0.22
      ansible_port: 10022
      ansible_user: root
    pihole-dns1:
      ansible_host: 192.168.0.8
      ansible_user: root
      ansible_port: 10022
    home-assistant-dc1:
      ansible_host: 192.168.0.35
      ansible_user: root
    saturn-builder-gitlab:
      ansible_host: 192.168.0.53
      ansible_user: root

physical:
  hosts:
    spider-prxmx:

virtual:
  hosts:
    pihole-dns1:
    home-assistant-dc1:
    saturn-builder-gitlab: