- name: ssh
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: ssh

- name: minimal_packages
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: minimal_packages

- name: bashrc
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: bashrc

- name: update_motd
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: update_motd

- name: cron
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: cron

- name: swapfile
  src: git@gitlab.com:raifcoonjah/homelab.git
  scm: git
  version: swapfile

- name: syncthing
  src: https://github.com/raifcoonjah/syncthing.git
  version: master
