---
- name: Update servers hosts
  hosts: all

  tasks:
    - name: Refresh repository (debian)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['distribution'] == "Debian"
    - name: Update packages (debian)
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "Debian"
    - name: Remove useless packages from the cache (debian)
      ansible.builtin.apt:
        autoclean: yes
      when: ansible_facts['distribution'] == "Debian"
    - name: Update using dnf (fedora)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "Fedora"
    - name: Update using apk (alpine)
      community.general.apk:
        upgrade: true
      when: ansible_facts['distribution'] == "Alpine"
