services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      MODEL: "TimeCapsule"
      AVAHI_NAME: "whonnik"
      SAMBA_CONF_LOG_LEVEL: 3
      GROUP_sambagroup: 1001
      ACCOUNT_raif: "${PASSWORD}"
      UID_raif: 1002
      GROUPS_john_doe: sambagroup

      SAMBA_VOLUME_CONFIG_shared_data: |
        [Shared Folder]
          path = /home/shared
          valid users = raif  #Remove if not using
          guest ok = no
          browseable = yes
          read only = no

    volumes:
      - /etc/avahi/services/:/external/avahi
      - /home/shared/:/home/shared
