---
- name: Copy weekly backup script (mv-backup.sh)
  ansible.builtin.template:
    src: mv-backup.j2
    dest: "{{ script_path }}/mv-backup.sh"
    owner: root
    group: root
    mode: "0770"

- name: Copy backup service
  ansible.builtin.template:
    src: proxmox-backup-service.j2
    dest: /lib/systemd/system/vm_backup.service
    mode: "0644"

- name: Copy backup timer
  ansible.builtin.template:
    src: proxmox-backup-timer.j2
    dest: /lib/systemd/system/vm_backup.timer
    mode: "0644"

- name: Enable backup service
  ansible.builtin.systemd_service:
    name: vm_backup.service
    enabled: true
    daemon_reload: true
