---
- name: Update servers hosts
  hosts: all

  tasks:
    - name: Refresh repository
      ansible.builtin.apt:
       update_cache: true
      when: ansible_facts['distribution'] == "Debian"
    - name: Update using dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "Fedora"
    - name: Update packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "Debian"
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes
      when: ansible_facts['distribution'] == "Debian"
    - name: Update beszel monitoring
      ansible.builtin.shell: "/opt/beszel/beszel update"
      ignore_errors: true
    - name: Update beszel agent
      ansible.builtin.shell: "/opt/beszel-agent/beszel-agent update"
      ignore_errors: true
    - name: Restart services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: restarted
      with_items: 
          - beszel-agent
          - beszel-hub

