---
# tasks file for cron
- name: Install cron
  ansible.builtin.package:
    name: cron
    state: present

- name: Enable cron service
  ansible.builtin.systemd_service:
    name: cron
    state: started
    enabled: true

- name: Copy generic cron
  ansible.builtin.template:
    src: apollo-generic.j2
    dest: /etc/cron.d/apollo-generic
    owner: root
    group: root
    mode: '0644'

- name: Copy syncthing specific cron
  ansible.builtin.template:
    src: syncthing-cron.j2
    dest: /etc/cron.d/syncthing-cron
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['syncthing']

- name: Copy proxmu1 specific cron
  ansible.builtin.template:
    src: proxmu1-cron.j2
    dest: /etc/cron.d/proxmu1-cron
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['physical'] and inventory_hostname == 'graviton'

- name: Copy whonnik specific cron
  ansible.builtin.template:
    src: whonnik-cron.j2
    dest: /etc/cron.d/whonnik-cron
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['physical'] and inventory_hostname == 'whonnik'


- name: Copy  gv-pihole specific cron
  ansible.builtin.template:
    src: pihole-cron.j2
    dest: /etc/cron.d/gv-pihole-cron
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == 'gv-pihole'
