---
- name: Copy authorized file
  ansible.builtin.template:
    src: "authorized_keys.j2"
    dest: '{{ authkey_path }}/authorized_keys'
    owner: root
    group: root
    mode: '600'
    backup: true

- name: Copy ssh configuration file
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: '/etc/ssh/ssh_config.d/apollo-router.conf'
    owner: root
    group: root
    mode: '600'
    backup: true

- name: Decrease MaxAuthTries
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    insertafter: '^#MaxAuthTries 6'
    line: 'MaxAuthTries 3'

- name: Enforce use of protocol 2
  ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    insertafter: '^Include /etc/ssh/sshd_config.d/*.conf'
    line: 'Protocol 2'
