---
- name: Copy disk file
  template:
    src: 'disk_health.j2'
    dest: '{{ locationdir }}/disk_health.sh'

- name: Copy docker_status file
  template:
     src: 'docker_status.j2'
     dest: '{{ locationdir }}/docker_status.sh'

- name: Copy fallback file
  template:
     src: 'fall-back.j2'
     dest: '{{ locationdir }}/fall-back.sh'

- name: Copy high load file
  template:
     src: 'high_load.j2'
     dest: ' {{ locationdir }}/high_load.sh'
