---
- name: Copy ssh config
  ansible.builtin.template:
    src: "./templates/ssh_config.j2"
    dest: '{{ authkey_path }}/config'
    owner: root
    group: root
    mode: '600'
    backup: true
    