---
- name: Install minimal packages
  ansible.builtin.apt:
      name: "{{ item }}"
      state: present
  with_items:
    - "{{ minimal_packages }}"

- name: Allow cloudinit root user
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^disable_root: true'
    line: "disable_root: false"  