---
- name: Install minimal packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minimal_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install minimal packages on Alpine Linux
  community.general.apk:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minimal_packages }}"
  when: ansible_facts['distribution'] == "Alpine"
