---
- name: Install minimal packages on Debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minimal_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install minimal packages on Alpine Linux
  community.general.apk:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minimal_packages }}"
  when: ansible_facts['distribution'] == "Alpine"

- name: Install minimal packages on openSUSE
  community.general.zypper:
    name: "{{ item }}"
    state: present
  loop: "{{ minimal_packages }}"
  when: ansible_facts['distribution'] in ['openSUSE Leap', 'openSUSE Tumbleweed']