---
- name: Update package cache
  ansible.builtin.package:
    update_cache: true

- name: Install minimal packages on Debian
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minimal_packages }}"
