all:
  vars:
    ansible_user: root
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    graviton:
      ansible_host: 192.168.100.20
    whonnik:
      ansible_host: 192.168.100.24
    gv-pihole:
      ansible_host: 192.168.100.5
    gv-syncthing:
      ansible_host: 192.168.100.11
    gv-ec2-gp1:
      ansible_host: 192.168.100.8

physical:
  hosts:
    graviton:
    whonnik:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    gv-pihole:
    gv-syncthing:
    gv-ec2-gp1:

syncthing:
  hosts:
    gv-pihole:
