all:
  vars:
    ansible_user: root
    # ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    graviton:
      ansible_host: 192.168.100.20
    whonnik:
      ansible_host: 192.168.100.24
    gv-pihole:
      ansible_host: 192.168.100.5
    gv-syncthing:
      ansible_host: 192.168.100.11
    gv-ec2-leap:
      ansible_host: 192.168.100.8
    PX-jellyfin-prod:
      ansible_host: 192.168.100.100
    gv-adguard-dns1:
      ansible_host: 192.168.100.6
    gv-adguard-dns2:
      ansible_host: 192.168.100.7

physical:
  hosts:
    graviton:
    whonnik:
  vars:
    ansible_port: 1922

virtual:
  hosts:
    gv-pihole:
    gv-syncthing:
    gv-ec2-leap:

syncthing:
  hosts:
    gv-syncthing:

dns:
  hosts:
    gv-adguard-dns1:
    gv-adgaurd-dns2:

mediaserver:
  hosts:
    PX-jellyfin-prod:
