---
- name: Deploy SSH Keys
  hosts: all

  tasks:
  - name: Copy new keys
    ansible.builtin.template:
       src: "./mytemplates/authorized_keys.j2"
       dest: '{{ authkey_path }}/authorized_keys'
       owner: root
       group: root
       mode: '600'
       backup: true