---
- name: Deploy SSH Keys
  hosts: all

  tasks:
  - name: Backup current authorized_keys file
    ansible.builtin.copy:
       src: '/root/.ssh/authorized_keys'
       dest: '/root/.ssh/authorized_keys.old'
       remote_src: yes
       owner: root
       group: root
       mode: '600'

  - name: Copy new keys
    ansible.builtin.template:
       src: "./mytemplates/authorized_keys.j2"
       dest: '{{ authkey_path }}/authorized_keys'
       owner: root
       group: root
       mode: '600'

