all:
  hosts:
    spider:
      ansible_host: 192.168.100.22
    adguard-master:
      ansible_host: 192.168.100.8

physical:
  vars:
    ansible_port: 10022
    ansible_user: root
  hosts:
    spider:

virtual:
  vars:
    ansible_port: 10022
    ansible_user: root
  hosts:
   adguard-master: