---
all:
  hosts:
    pihole:
      ansible_host: 192.168.100.8
    pluto-prxmx:
      ansible_host: 192.168.100.10
    vamiz1:
      ansible_host: 192.168.100.55
    vamiz2:
      ansible_host: 192.168.100.56
    docker-master:
      ansible_host: 192.168.100.60

physical:
  vars: # Groups vars
    ansible_port: 10022
    ansible_user: root
  hosts:
    pihole:
    pluto-prxmx:
virtual:
  vars:
    ansible_port: 10022
    ansible_user: root
  hosts:
    vamiz1:
    vamiz2:
    docker-master: