name: Check linting

on:
  push:
    branches:
      - main
      - refactor_codebase

jobs:
  chk_lint:
    runs-on: self-hosted

    steps:

    - name: Run ansible-lint
      run: |
        cd /etc/ansible/ansible/roles
        ansible-lint roles/* --exclude */meta/main.yml 
