name: Pull changes locally

on:
  push:
    branches:
      - '*'

jobs:
  deploycodebase:
    runs-on: self-hosted  # raif-lab1

    steps:
      - name: Check if ansible is installed
        run: ansible --version
      - name: Pull codebase locally
        run: |
          git -C /home/raif/homelab pull
