name: Update codebase on controller

on:
  push:
    branches:
      - main
      - refactor_codebase

jobs:
  update:
    runs-on: self-hosted

    steps:
    - name: Set target directory
      run: echo "TARGET_DIR=/etc/ansible" >> $GITHUB_ENV

    - name: Update or clone codebase
      run: |
        if [ -d "${{ env.TARGET_DIR }}/.git" ]; then
          cd "${{ env.TARGET_DIR }}"
          sudo git fetch origin
          sudo git reset --hard origin/refactor_codebase
          # No git pull needed after reset --hard
        else
          sudo git clone git@github.com:raifcoonjah/homelab.git "${{ env.TARGET_DIR }}"
        fi

    - name: Run ansible-lint
      run: |
        cd "${{ env.TARGET_DIR }}/ansible"
        ansible-lint roles/* --exclude '*/meta/main.yml'
      continue-on-error: false # we can ignore for failure for now, will fix this later

    - name: Check Ansible connectivity
      run: |
        cd "${{ env.TARGET_DIR }}/ansible"
        sudo ansible -m ping -i inventories/prod/hosts.yml all -u root --timeout=10
