name: Update codebase on controller

on:
  push:
    branches:
      - main
      - refactor_codebase

jobs:
  update:
    runs-on: self-hosted

    steps:
    - name: Clone codebase
      run: |
        TARGET_DIR="/etc/ansible"
        if [ -d "$TARGET_DIR/.git" ]; then
          cd $TARGET_DIR
          sudo /usr/bin/git fetch origin
          sudo /usr/bin/git reset --hard origin/refactor_codebase
          sudo /usr/bin/git pull --rebase
        else
          sudo /usr/bin/git clone git@github.com:raifcoonjah/homelab.git $TARGET_DIR
        fi

    - name: Run ansible-lint
      run: |
        cd /etc/ansible/ansible/ # temp path
        ansible-lint roles/* --exclude */meta/main.yml
      continue-on-error: true
    
    - name: Check connectivity
      run: |
        cd /etc/ansible/ansible
        sudo ansible -m ping -i inventories/prod/hosts.yml all -u root